### ISSUE TITLE
Esri Tiles Inverted

### ISSUE THREAD

**Issue by CorentinVisee** [riatelab/maptiles#34]
Hi, 

I am contacting you regarding a problem with Esri map tiles. The tiles seem to be reversed (north is south): 

```
library(maptiles)
library(terra)
library(geodata)

tanzania <- gadm(country = "Tanzania", level = 0, path = tempdir())

tanzania_tile <- get_tiles(x = tanzania, crop = T, verbose = T, provider = "Esri.WorldImagery") 

plot(tanzania_tile)
plot(tanzania, add = T, lwd = 2)
```
![image](https://github.com/user-attachments/assets/b68a4d63-6c5b-445a-a89e-da756332b881)

Or for Senegal
![image](https://github.com/user-attachments/assets/3ddea77d-b177-4f66-b389-cde0d15f8735)

Do you have any idea where the problem might come from? 

Thank you in advance for your help in this matter,
Kind regards, 
Corentin V.

**Comment by rCarto** [comment]
Yes! I'm aware of this problem. It comes from an update of the terra package. I've posted an issue there. https://github.com/rspatial/terra/issues/1627

A solution would be to downgrade the terra version. 
I'll keep this issue open untill the next terra version.

**Comment by CorentinVisee** [comment]
Thank you for your quick reply!

**Comment by rCarto** [comment]
It works now with the dev version of terra. See https://github.com/rspatial/terra/issues/1627#issuecomment-2478454885

**Comment by CorentinVisee** [comment]
Thank you ! :)

**Comment by rCarto** [comment]
Fixed in `terra`.

**Comment by evhersh** [comment]
Hello,

I came across this issue a couple months ago and updated to the terra dev build which fixed the issue, however I'm working on another map now and it appears to have reverted? I have just updated to the latest dev builds of maptiles and terra and I'm still getting inverted ESRI tiles. Any ideas what might be going on?

**Comment by rCarto** [comment]
I'll keep this issue open untill the next terra or maptiles version.

**Comment by rCarto** [comment]
Fixed on CRAN version.
